services:
  single-redis:
    image: docker.io/bitnami/redis-cluster:7.2
    volumes:
      - single-redis_data:/bitnami/redis/data
      - ./tls:/tls
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=single-redis'
      - 'REDIS_TLS_ENABLED=yes'
      - 'REDIS_TLS_CERT_FILE=/tls/redis.crt'
      - 'REDIS_TLS_KEY_FILE=/tls/redis.key'
      - 'REDIS_TLS_CA_FILE=/tls/ca.crt'
      - 'REDIS_TLS_DH_PARAMS_FILE=/tls/redis.dh'
      - 'REDIS_TLS_AUTH_CLIENTS=yes'
    ports:
      - 7000:6379

volumes:
  single-redis_data:
    driver: local
